# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBI
version:      1.54
version_from: DBI.pm
installdirs:  site
requires:
    File::Spec:                    1
    Storable:                      1
    Test::Simple:                  0.4

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
