From www@webmail.lf.net  Mon Jun  9 10:49:58 2003
Received: from localhost (localhost [127.0.0.1])
	by dansat.data-plan.com (8.12.9/8.12.9) with ESMTP id h599no0r043230
	for <timbo@localhost>; Mon, 9 Jun 2003 10:49:58 +0100 (BST)
	(envelope-from www@webmail.lf.net)
Received: from pop3.mail.demon.net [194.217.242.253]
	by localhost with POP3 (fetchmail-5.8.5)
	for timbo@localhost (single-drop); Mon, 09 Jun 2003 10:49:58 +0100 (BST)
Received: from punt-2.mail.demon.net by mailstore for Tim.Bunce@data-plan.com
          id 1055151227:20:05173:26; Mon, 09 Jun 2003 09:33:47 GMT
Received: from icicle-214-2.pobox.com ([207.8.214.2]) by punt-2.mail.demon.net
           id aa2005474; 9 Jun 2003 9:33 GMT
Received: from icicle.pobox.com (localhost [127.0.0.1])
	by icicle.pobox.com (Postfix) with ESMTP id 5FF9058276
	for <Tim.Bunce@data-plan.com>; Mon,  9 Jun 2003 05:32:58 -0400 (EDT)
Delivered-To: tim.bunce@pobox.com
Received: from webmail.LF.net (webmail.LF.net [212.9.160.14])
	by icicle.pobox.com (Postfix) with ESMTP id DF4D058310
	for <Tim.Bunce@pobox.com>; Mon,  9 Jun 2003 05:32:57 -0400 (EDT)
Received: from www by webmail.LF.net with local (Exim 4.14)
	id 19PJ1M-0002fF-62; Mon, 09 Jun 2003 11:32:56 +0200
To: Tim Bunce <Tim.Bunce@pobox.com>
Subject: Re: Proposed patches for PlRPC and Proxy
Message-ID: <1055151176.3ee45448162a7@webmail.LF.net>
Date: Mon, 09 Jun 2003 11:32:56 +0200 (CEST)
From: Jochen Wiedmann <joe@ispsoft.de>
Cc: "Steven N. Hirsch" <hirschs@btv.ibm.com>, dbi-dev@perl.org
References: <Pine.LNX.4.33.0305091102370.1773-100000@bucky.btv.ibm.com> <20030510212815.GA12263@dansat.data-plan.com>
In-Reply-To: <20030510212815.GA12263@dansat.data-plan.com>
MIME-Version: 1.0
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: 8bit
User-Agent: IMP/PHP IMAP webmail program 2.2.6
X-Originating-IP: 193.26.194.2
Sender: WWW <www@webmail.lf.net>
Status: RO
X-Status: A
Content-Length: 340
Lines: 11

Quoting Tim Bunce <Tim.Bunce@pobox.com>:

> I've CC'd Jochen as he needs to apply the PlRPC patches and make a
> new release before I can depend on them being available.

Done. Besides, Tim, I have no problems if you apply any changes.
As we all know, it is very unlikely that I'll be actively developing
the module in the future.


Jochen

