From dbi-users-return-21178-Tim.Bunce=pobox.com@perl.org  Sun Dec  7 18:35:58 2003
Received: from localhost (localhost [127.0.0.1])
	by dansat.data-plan.com (8.12.9/8.12.9) with ESMTP id hB7IY1o5096618
	for <timbo@localhost>; Sun, 7 Dec 2003 18:35:58 GMT
	(envelope-from dbi-users-return-21178-Tim.Bunce=pobox.com@perl.org)
Received: from pop3.mail.demon.net [194.217.242.253]
	by localhost with POP3 (fetchmail-5.8.5)
	for timbo@localhost (single-drop); Sun, 07 Dec 2003 18:35:58 +0000 (GMT)
Received: from punt-3.mail.demon.net by mailstore
	for pobox@dbi.demon.co.uk id 1AT2s7-00011a-48;
	Sun, 07 Dec 2003 17:39:07 +0000
Received: from [216.65.124.72] (helo=orb.pobox.com)
	by punt-3.mail.demon.net with esmtp id 1AT2s7-00011a-48
	for pobox@dbi.demon.co.uk; Sun, 07 Dec 2003 17:39:07 +0000
Received: from orb.pobox.com (localhost[127.0.0.1])
	by orb.pobox.com (Postfix) with ESMTP id 3253D2E14E3
	for <pobox@dbi.demon.co.uk>; Sun,  7 Dec 2003 12:39:06 -0500 (EST)
Delivered-To: tim.bunce@pobox.com
Received: from colander (localhost[127.0.0.1])
	by orb.pobox.com (Postfix) with ESMTP id 0EE372E14A7
	for <Tim.Bunce@pobox.com>; Sun,  7 Dec 2003 12:39:06 -0500 (EST)
Received: from onion.perl.org (onion.develooper.com[63.251.223.166])
	by orb.pobox.com (Postfix) with SMTP
	for <Tim.Bunce@pobox.com>; Sun,  7 Dec 2003 12:39:05 -0500 (EST)
Received: (qmail 90705 invoked by uid 1005); 7 Dec 2003 17:38:57 -0000
Mailing-List: contact dbi-users-help@perl.org; run by ezmlm
Precedence: bulk
List-Post: <mailto:dbi-users@perl.org>
List-Help: <mailto:dbi-users-help@perl.org>
List-Unsubscribe: <mailto:dbi-users-unsubscribe@perl.org>
List-Subscribe: <mailto:dbi-users-subscribe@perl.org>
Delivered-To: mailing list dbi-users@perl.org
Received: (qmail 90685 invoked by uid 76); 7 Dec 2003 17:38:56 -0000
Received: from x1.develooper.com (HELO x1.develooper.com) (63.251.223.170) by onion.perl.org (qpsmtpd/0.26) with SMTP; Sun, 07 Dec 2003 09:38:56 -0800
Received: (qmail 9649 invoked by uid 225); 7 Dec 2003 17:38:54 -0000
Delivered-To: dbi-users@perl.org
Received: (qmail 9645 invoked by alias); 7 Dec 2003 17:38:54 -0000
Received: from mail2.speakeasy.net (HELO mail2.speakeasy.net) (216.254.0.202) by la.mx.develooper.com (qpsmtpd/0.27-dev) with ESMTP; Sun, 07 Dec 2003 09:38:42 -0800
Received: (qmail 20579 invoked from network); 7 Dec 2003 17:38:39 -0000
Received: from unknown (HELO vpservices.com) (jzucker@[66.93.39.31])          (envelope-sender <jeff@vpservices.com>)          by mail2.speakeasy.net (qmail-ldap-1.03) with AES256-SHA encrypted SMTP          for <dbi-users@perl.org>; 7 Dec 2003 17:38:39 -0000
Message-ID: <3FD3658E.6070402@vpservices.com>
Date: Sun, 07 Dec 2003 09:38:22 -0800
From: Jeff Zucker <jeff@vpservices.com>
User-Agent: Mozilla/5.0 (Windows; U; Win98; en-US; rv:1.5) Gecko/20031007
X-Accept-Language: en-us, en
MIME-Version: 1.0
To: dbi-users <dbi-users@perl.org>
Subject: Discussion of Data Modeling Tools
Content-Type: text/plain; charset=ISO-8859-1; format=flowed
Content-Transfer-Encoding: 7bit
X-Spam-Check-By: la.mx.develooper.com
X-Spam-Status: No, hits=-0.5 required=7.0 tests=CARRIAGE_RETURNS,SPAM_PHRASE_00_01,TO_LOCALPART_EQ_REAL,USER_AGENT,USER_AGENT_MOZILLA_UA,X_ACCEPT_LANG version=2.44
X-SMTPD: qpsmtpd/0.26, http://develooper.com/code/qpsmtpd/
Status: RO
Content-Length: 277
Lines: 11

There are some informative posts in Slashdot's article on data modeling 
tools that may be of interest to some on this list:

    http://ask.slashdot.org/article.pl?sid=03/12/06/018207

It looks like Dia and its offshoots may yet provide an open source 
contender. 

-- 
Jeff


