From s.goeldner@eurodata.de  Fri Dec 19 19:23:32 2003
Received: from localhost (localhost [127.0.0.1])
	by dansat.data-plan.com (8.12.9/8.12.9) with ESMTP id hBJJN7mq024205
	for <timbo@localhost>; Fri, 19 Dec 2003 19:23:32 GMT
	(envelope-from s.goeldner@eurodata.de)
Received: from pop3.mail.demon.net [194.217.242.253]
	by localhost with POP3 (fetchmail-5.8.5)
	for timbo@localhost (single-drop); Fri, 19 Dec 2003 19:23:32 +0000 (GMT)
Received: from punt-3.mail.demon.net by mailstore
	for pobox@dbi.demon.co.uk id 1AXML9-0006sh-84;
	Fri, 19 Dec 2003 19:03:05 +0000
Received: from [207.8.214.3] (helo=puzzle.pobox.com)
	by punt-3.mail.demon.net with esmtp id 1AXML9-0006sh-84
	for pobox@dbi.demon.co.uk; Fri, 19 Dec 2003 15:14:55 +0000
Received: from puzzle.pobox.com (localhost [127.0.0.1])
	by puzzle.pobox.com (Postfix) with ESMTP id 2FC4B17415B
	for <pobox@dbi.demon.co.uk>; Fri, 19 Dec 2003 10:14:33 -0500 (EST)
Delivered-To: tim.bunce@pobox.com
Received: from colander (localhost [127.0.0.1])
	by puzzle.pobox.com (Postfix) with ESMTP id 3EFCB176448
	for <Tim.Bunce@pobox.com>; Fri, 19 Dec 2003 10:14:31 -0500 (EST)
Received: from mail1.ncc.eurodata.de (mail1.ncc.eurodata.de [212.89.134.25])
	by puzzle.pobox.com (Postfix) with ESMTP
	for <Tim.Bunce@pobox.com>; Fri, 19 Dec 2003 10:14:19 -0500 (EST)
Received: from vscan1.ncc.eurodata.de (vscan1.ncc.eurodata.de [212.89.134.21])
	by mail1.ncc.eurodata.de (Postfix) with ESMTP id B0F4B14C14A
	for <Tim.Bunce@pobox.com>; Fri, 19 Dec 2003 16:14:16 +0100 (CET)
Received: by vscan1.ncc.eurodata.de (Postfix, from userid 8)
	id 7DB2756CCE; Fri, 19 Dec 2003 16:14:16 +0100 (CET)
Received: from localhost (localhost [127.0.0.1])
	by vscan1.ncc.eurodata.de (Postfix) with ESMTP id 44E5F56CCD
	for <Tim.Bunce@pobox.com>; Fri, 19 Dec 2003 16:14:16 +0100 (CET)
Received: from eurodata.de (mail-redir.eurodata.de [10.2.2.50])
	by mail1.ncc.eurodata.de (Postfix) with ESMTP id 1CBE214C14B
	for <Tim.Bunce@pobox.com>; Fri, 19 Dec 2003 16:14:16 +0100 (CET)
Message-ID: <3FE315EB.A46E3B73@eurodata.de>
Date: Fri, 19 Dec 2003 16:14:51 +0100
From: Steffen Goeldner <s.goeldner@eurodata.de>
Organization: eurodata GmbH & Co.KG
X-Mailer: Mozilla 4.04 [en] (WinNT; I)
MIME-Version: 1.0
To: Tim.Bunce@pobox.com
Subject: Re: DBI: type_info_all doc
References: <3FB8922A.4048CAD1@eurodata.de>
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit
X-Scanned-By: AMaViS-ng (vscan1) at eurodata.
Status: RO
X-Status: A
Content-Length: 242
Lines: 12

Tim,

did you receive this patch?

  <http://www.xray.mpe.mpg.de/mailing-lists/dbi/2003-11/msg00209.html>

FYI: I'm away for 2-3 weeks (thus I cannot test your
Hogmanay release of DBD::Oracle ;-)


Merry Christmas and Happy New Year!
Steffen

