From Tim.Bunce@pobox.com  Mon May 19 14:24:14 2003
Received: from localhost (localhost [127.0.0.1])
	by dansat.data-plan.com (8.12.6/8.12.6) with ESMTP id h4JDOD2f015979
	for <timbo@localhost>; Mon, 19 May 2003 14:24:14 +0100 (BST)
	(envelope-from Tim.Bunce@pobox.com)
Delivered-To: eircom.net-timbunce@eircom.net
X-Envelope-To: timbunce@eircom.net
Received: from mail1.eircom.net [159.134.198.135]
	by localhost with POP3 (fetchmail-5.8.5)
	for timbo@localhost (single-drop); Mon, 19 May 2003 14:24:14 +0100 (BST)
Received: (vpopmail 72180 invoked by uid 16); 19 May 2003 10:42:34 +0100
Received: (qmail 72152 messnum 1153312 invoked from network[159.134.166.153/p665.as1.limerick1.eircom.net]); 19 May 2003 09:42:33 -0000
Received: from p665.as1.limerick1.eircom.net (HELO dansat.data-plan.com) (159.134.166.153)
  by mail04.svc.cra.dublin.eircom.net (qp 72152) with SMTP; 19 May 2003 09:42:33 -0000
Received: from pobox.com (localhost [127.0.0.1])
	by dansat.data-plan.com (8.12.6/8.12.6) with ESMTP id h4J9gZ2f015617
	for <timbunce@eircom.net>; Mon, 19 May 2003 10:42:36 +0100 (BST)
	(envelope-from Tim.Bunce@pobox.com)
Message-ID: <3EC8A70B.3020508@pobox.com>
Date: Mon, 19 May 2003 10:42:35 +0100
From: Tim Bunce <Tim.Bunce@pobox.com>
User-Agent: Mozilla/5.0 (X11; U; FreeBSD i386; en-US; rv:0.9.4) Gecko/20011108
X-Accept-Language: en-us
MIME-Version: 1.0
To: timbunce <timbunce@eircom.net>
Subject: Index of /SC32/SQL_Registry
X-UIDL: 1053337354.72180.mail04.svc.cra.dublin.eircom.net,S=984
Content-Type: text/plain; charset=us-ascii; format=flowed
Content-Transfer-Encoding: 7bit
Status: RO
Content-Length: 46
Lines: 3


<ftp://sqlstandards.org/SC32/SQL_Registry/>


